### ISSUE TITLE
resourcestream closed

### ISSUE THREAD

**Issue by gonline** [cincuranet/SingleExecutable#1]
https://github.com/cincuranet/SingleExecutable/blob/24ac06e7b34f19a4910dc70654ae18d578386b79/SingleExecutable/InjectMe.cs#L93

Hi

I'm having a "cannot access a closed stream" in method SaveToDisk.SetPosition.
This is because the binary reader by default closes the stream.
I think there is a property on binary reader, LeaveOpen that prevents this.
It is also part of the constructor.

https://msdn.microsoft.com/en-us/library/gg712804(v=vs.110).aspx

kind regards

Alexander

**Comment by cincuranet** [comment]
Solved in [2.1.1](https://www.nuget.org/packages/SingleExecutable/2.1.1).
