### ISSUE TITLE
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly:..

### ISSUE THREAD

**Issue by k4m4r82** [cincuranet/SingleExecutable#4]
Hi, i got error when use this library. How to fix it?

![error](https://user-images.githubusercontent.com/6903970/50976340-4ad42800-1522-11e9-9776-ac79001907bb.png)

My project use .NET Framework 4.0

**Comment by cincuranet** [comment]
Do you have the mentioned assembly there?

**Comment by k4m4r82** [comment]
I use this project https://github.com/rudi-krsoftware/open-retail for testing

**Comment by cincuranet** [comment]
That's not what I was asking for.

**Comment by k4m4r82** [comment]
> Do you have the mentioned assembly there?

Yes, i do

![error2](https://user-images.githubusercontent.com/6903970/50978663-7b6a9080-1527-11e9-9db2-500a74b2cfe9.png)

**Comment by cincuranet** [comment]
If you can upload the folder with files somewhere and the command line you're using I can try it and see. Nothing from top of my head now to resolve it.

**Comment by k4m4r82** [comment]
ok, you can download it from here https://drive.google.com/open?id=1SS8T8fa-lid2vOV6co6W4QZF-Bot2bW2

for the command line, I use it like this:

`SingleExecutable -e "E:\OpenRetailer\deploy\bin\OpenRetail.exe" -o "E:\OpenRetailer\deploy\OpenRetail.exe" -a "E:\OpenRetailer\deploy\bin\OpenRetail.exe.config"`

**Comment by cincuranet** [comment]
Fixed in [version 2.3.0](https://www.nuget.org/packages/SingleExecutable/2.3.0). Now, alternatively you can (should) call `SingleExecutable.exe` in the same directory as the executable you're packing.
